export const environment = {
  production: true,
  WEB_SITE_NAME: 'TravelTech - SR',
  serviceRequest_url: 'http://travsr.dev.com/servicerequest',
  searchPax_Proxy_Url: 'http://travsr.dev.com/paxdata/',
  masterData_Proxy_Url: 'http://travsr.dev.com/jdbcapi/',
  companyMasterData_Proxy_Url: 'http://travsr.dev.com/system-master/',
  businessList_Proxy_Url: 'http://travsr.dev.com/paxdata/',
  USERMANAGEMENT: 'http://travsr.dev.com/usermanagement/',
  RFQ: 'http://travsr.dev.com/option/',
  loginAfterHit: 'http://travpx.dev.com/tt-micro-services_v1/',
  Quote: 'http://travpx.dev.com/tt-ci-quote_v1/',
  BPF: 'http://travsr.dev.com/bpf/',
  flightBooking: 'http://travsr.dev.com/flight-api/',
  storeManagement: 'http://travsr.dev.com/store-management/',
  ResourcesAssignment: 'http://travsr.dev.com/resources-assignment/',
  RFQREDIRECTOFFLINE: 'http://travpx.dev.com/tt-ci-app_v1/',
  HOTELOFFLINE: 'http://192.178.10.123/srm/',
  ENVIRONMENT_MODE: 'dev',
  E_SERVICE_DYNAMIC_HOST: 'http://travsr.dev.com',
  SERVICE_CONFIG: 'http://travsr.dev.com/travrconfig/',
  FLEX_PRICE: 'https://test.api.amadeus.com/v2/shopping/flight-offers',
  Flex_Auth: 'https://test.api.amadeus.com/v1/',
  AMADEUSTOKEN: 'https://test.api.amadeus.com/v1/security/oauth2/token',
  TT_MAIL_BOX: 'http://travpx.dev.com/tt-email/',
  TT_MAIL_BOX_1: 'http://travpx.dev.com/tt-email/',
  PAYMENT: 'http://travpx.dev.com/tt-ci-fin_v1/',
  TTCHAT: ' http://travpx.dev.com/tt-chat/',
  TT_CHAT_NODE: 'http://192.178.10.122:3421',
  SOCKET_ENDPOINT: 'http://travwtapi.dev.com:6100',
  WATICKETURL: 'http://travwt.dev.com/',
  WHATSAPP: 'https://api.whatsapp.com/',
  REFRESHTOKEN: 'http://travsr.dev.com/fe-login-management/',
  EMPLOYEE: 'http://travsr.dev.com/hr/',
  packageAddPrice: 'http://travsr.dev.com/packages/',
  reports: 'http://travsr.dev.com/reports/',
  CRYPTO_SK:'WnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/',
  CRYPTO_IV:'A%D*G-KaPdSgVkXp',
  CBTUSER: "http://travpx.dev.com/cbt-user/",
  DEALS: "http://travsr.dev.com/deals/",
};



