// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.
//Dev  development
/*   export const environment = {
  production: true,
  WEB_SITE_NAME: 'TravelTech - SR',
  serviceRequest_url: 'http://travsr.dev.com/servicerequest',
  searchPax_Proxy_Url: 'http://travsr.dev.com/paxdata/',
  masterData_Proxy_Url: 'http://travsr.dev.com/jdbcapi/',
  companyMasterData_Proxy_Url: 'http://travsr.dev.com/system-master/',
  businessList_Proxy_Url: 'http://travsr.dev.com/paxdata/',
  USERMANAGEMENT: 'http://travsr.dev.com/usermanagement/',
  RFQ: 'http://travsr.dev.com/option/',
  loginAfterHit: 'http://travpx.dev.com/tt-micro-services_v1/',
  Quote: 'http://travpx.dev.com/tt-ci-quote_v1/',
  BPF: 'http://travsr.dev.com/bpf/',
  flightBooking: 'http://travsr.dev.com/flight-api/',
  storeManagement: 'http://travsr.dev.com/store-management/',
  ResourcesAssignment: 'http://travsr.dev.com/resources-assignment/',
  RFQREDIRECTOFFLINE: 'http://travpx.dev.com/tt-ci-app_v1/',
  HOTELOFFLINE: 'http://192.178.10.123/srm/',
  ENVIRONMENT_MODE: 'dev',
  E_SERVICE_DYNAMIC_HOST: 'http://travsr.dev.com',
  SERVICE_CONFIG: 'http://travsr.dev.com/travrconfig/',
  FLEX_PRICE: 'https://test.api.amadeus.com/v2/shopping/flight-offers',
  Flex_Auth: 'https://test.api.amadeus.com/v1/',
  AMADEUSTOKEN: 'https://test.api.amadeus.com/v1/security/oauth2/token',
  TT_MAIL_BOX: 'http://travpx.dev.com/tt-email/',
  TT_MAIL_BOX_1: 'http://travpx.dev.com/tt-email/',
  PAYMENT: 'http://travpx.dev.com/tt-ci-fin_v1/',
  TTCHAT: ' http://travpx.dev.com/tt-chat/',
  TT_CHAT_NODE: 'http://192.178.10.122:3421',
  SOCKET_ENDPOINT: 'http://travwtapi.dev.com:6100',
  WATICKETURL: 'http://travwt.dev.com/',
  WHATSAPP: 'https://api.whatsapp.com/',
  REFRESHTOKEN: 'http://travsr.dev.com/fe-login-management/',
  EMPLOYEE: 'http://travsr.dev.com/hr/',
  packageAddPrice: 'http://travsr.dev.com/packages/',
  reports: 'http://travsr.dev.com/reports/',
  CRYPTO_SK:'WnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/',
  CRYPTO_IV:'A%D*G-KaPdSgVkXp',
  CBTUSER: "http://travpx.dev.com/cbt-user/",
  DEALS: "http://travsr.dev.com/deals/",

}; */


/*UATSetup*/

//  export const environment = {
//    production: true,
//    WEB_SITE_NAME: 'TravelTech - SR',
//    serviceRequest_url: 'http://uattravsr.dev.com/servicerequest',
//    searchPax_Proxy_Url: 'http://uattravsr.dev.com/paxdata/',
//    masterData_Proxy_Url: 'http://uattravsr.dev.com/jdbcapi/',
//    companyMasterData_Proxy_Url: 'http://uattravsr.dev.com/system-master/',
//    businessList_Proxy_Url: 'http://uattravsr.dev.com/paxdata/',
//    USERMANAGEMENT: 'http://uattravsr.dev.com/usermanagement/',
//    RFQ: 'http://uattravsr.dev.com/option/',
//    loginAfterHit: 'http://uattravpx.dev.com/tt-micro-services_v1/',
//    Quote: 'http://uattravpx.dev.com/tt-ci-quote_v1/',
//    BPF: 'http://uattravsr.dev.com/bpf/',
//    flightBooking: 'http://uattravsr.dev.com/flight-api/',
//    storeManagement: 'http://uattravsr.dev.com/store-management/',
//    ResourcesAssignment: 'http://uattravsr.dev.com/resources-assignment/',
//    RFQREDIRECTOFFLINE: 'http://uattravpx.dev.com/tt-ci-app_v1/',
//    HOTELOFFLINE: 'http://192.178.10.123/srm/',
//    ENVIRONMENT_MODE: 'uat',
//    E_SERVICE_DYNAMIC_HOST: 'http://uattravsr.dev.com',
//    SERVICE_CONFIG: 'http://uattravsr.dev.com/travrconfig/',
//    FLEX_PRICE: 'https://test.api.amadeus.com/v2/shopping/flight-offers',
//    Flex_Auth: 'https://test.api.amadeus.com/v1/',
//    AMADEUSTOKEN: 'https://test.api.amadeus.com/v1/security/oauth2/token',
//    TT_MAIL_BOX: 'http://uattravpx.dev.com/tt-email/',
//    TT_MAIL_BOX_1: 'http://uattravpx.dev.com/tt-email/',
//    PAYMENT: 'http://uattravpx.dev.com/tt-ci-fin_v1/',
//    TTCHAT: ' http://uattravpx.dev.com/tt-chat/',
//    TT_CHAT_NODE: 'http://192.178.10.148:3421',
//    SOCKET_ENDPOINT: 'http://uattravwtapi.dev.com:6100',
//    WATICKETURL: 'http://uattravwt.dev.com/',
//    WHATSAPP: 'https://api.whatsapp.com/',
//    REFRESHTOKEN: 'http://uattravsr.dev.com/fe-login-management/',
//    EMPLOYEE: 'http://uattravsr.dev.com/hr/',
//    packageAddPrice: 'http://uattravsr.dev.com/packages/',
//    reports: 'http://uattravsr.dev.com/reports/',
//    CRYPTO_SK:'WnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/',
//    CRYPTO_IV:'A%D*G-KaPdSgVkXp',
//    CBTUSER: "http://uattravpx.dev.com/cbt-user/",
//    DEALS: "http://uattravsr.dev.com/deals/",
//  };



//local development
  export const environment = {
  production: false,
  WEB_SITE_NAME: "TravelTech - SR",
  serviceRequest_url: 'apiServiceRequest',
  searchPax_Proxy_Url: '/apiPax/',
  masterData_Proxy_Url: '/apiMasterData/',
  companyMasterData_Proxy_Url: '/apiSearchData/',
  businessList_Proxy_Url: '/apiPax',
  USERMANAGEMENT: 'userManagement/',
  RFQ: 'apiRFQ/',
  loginAfterHit: '/loginAfterHitApi/',
  BPF: '/BPF',
  flightBooking: '/flightBooking/',
  storeManagement: '/store-management/',
  ResourcesAssignment: '/resources-assignment/',
  TT_MAIL_BOX: 'http://travpx.dev.com/tt-email/',
  TT_MAIL_BOX_1: 'TT_MAIL_BOX/',
  RFQREDIRECTOFFLINE: 'http://travpx.dev.com/tt-ci-app_v1/',
  Quote: 'http://travpx.dev.com/tt-ci-quote_v1/',
  HOTELOFFLINE: 'http://192.178.10.123/srm/',
  ENVIRONMENT_MODE: 'localhost',
  E_SERVICE_DYNAMIC_HOST: 'domainName',
  SERVICE_CONFIG: 'serviceConfig/',
  FLEX_PRICE: 'https://test.api.amadeus.com/v2/shopping/flight-offers',
  Flex_Auth: 'https://test.api.amadeus.com/v1/',
  AMADEUSTOKEN: 'https://test.api.amadeus.com/v1/security/oauth2/token',
  FINANCE: 'http://travfin.dev.com/',
  PAYMENT: 'http://travpx.dev.com/tt-ci-fin_v1/',
  TTCHAT: 'http://travpx.dev.com/tt-chat/',
  TT_CHAT_NODE: 'http://192.178.10.122:3421',
  //SOCKET_ENDPOINT: 'http://localhost:8080',
  SOCKET_ENDPOINT: 'http://travwtapi.dev.com:6100',
  WATICKETURL: 'http://localhost:3000/',
  WHATSAPP: 'https://api.whatsapp.com/',
  REFRESHTOKEN: 'refreshTokenFeLoginManagement/',
  EMPLOYEE: '/hr/',
  packageAddPrice: 'packages/',
  reports: 'reports/',
  CRYPTO_SK:'WnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/',
  CRYPTO_IV:'A%D*G-KaPdSgVkXp',
  CBTUSER: "http://travpx.dev.com/cbt-user/",
  DEALS:  "deals/",
};

