import { RouteInfo } from './vertical-menu.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [

  {
    path: '/dashboard/cash-management/cash-dashboard',
    title: 'DashBoard',
    icon: 'ft-home',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
  }
  ,
  {
    path: '',
    title: 'Request',
    icon: 'ft-git-pull-request',
    class: 'has-sub',
    badge: '',
    badgeClass: 'badge badge-pill badge-danger float-right mr-1 mt-1',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/request/pax-search',
        title: 'Create Request',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/request/all-service-requests',
        title: 'Requests List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/request/package-request-list',
        title: 'Package Requests List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      }
    ],
  },
  {
    path: '',
    title: 'Packages',
    icon: 'ft-briefcase ',
    class: 'has-sub',
    badge: '',
    badgeClass: 'badge badge-pill badge-danger float-right mr-1 mt-1',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/packages/add-price',
        title: 'Price Add',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/packages/price-list',
        title: 'Price List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },


    ],
  },
  {
    path: '',
    title: 'RFQ',
    icon: 'icon-envelope-letter',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/rfq/product-based-list',
        title: 'RFQ-List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/rfq/supplier-information',
        title: 'RFQ-Flight',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/rfq/hotel-rfqs-awt-response',
        title: 'RFQ-Hotel',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/rfq/ancillary-rfqs-awt-response',
        title: 'RFQ-Ancillary',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/rfq/attractions-awt-response',
        title: 'RFQ-Attractions',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/rfq/package-rfq',
        title: 'RFQ-Package',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/rfq/open',
        title: 'RFQ Open List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/rfq/submitted',
        title: 'RFQ Submitted List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Quotes',
    icon: 'icon-doc',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/quotes/open',
        title: 'Quotes Open List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/quotes/submitted',
        title: 'Quotes Sent List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/quotes/approved',
        title: 'Quotes Approved List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Reports',
    icon: 'ft-bar-chart-2',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/reports/booking/view',
        title: 'Booking Report',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/reports/sr-summary-list',
        title: 'Sr Summary  Report',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      }


    ],
  },
  {
    path: '',
    title: 'Adjustments',
    icon: 'ft-file-text',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/dashboard/adj/corporate-to-retail',
        title: 'Corporate To Retail',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      },
      {
        path: '/dashboard/adj/retail-to-corporate',
        title: 'Retail To Corporate',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
      }

    ],
  },

  {
    path: '',
    title: 'Finance',
    icon: 'fa fa-money',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: 'http://travfin.dev.com/dashboard/lpo/receive',
        title: 'Create LPO',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      },
      {
        path: 'http://travfin.dev.com/dashboard/invoice/receive-invoice',
        title: 'Create Invoice',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      },

      {
        path: 'http://travpx.dev.com/tt-ci-fin_v1/receipt/create',
        title: 'Create Receipt',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      },
      {
        path: 'http://travpx.dev.com/tt-ci-fin_v1/payment/create',
        title: 'Create Payment',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      }
    ],
  },
  {
    path: '',
    title: 'Apps',
    icon: 'icon-screen-desktop',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: 'http://travcx.dev.com/dashboard/home',
        title: 'CX',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      },
      {
        path: 'http://travusrm.dev.com/dashboard/home',
        title: 'Usrm',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      },

      {
        path: 'http://travpic.dev.com/dashboard/home',
        title: 'Pic',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      },
      {
        path: 'http://travbpf.dev.com/dashboard/home',
        title: 'BPF',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      },
      {
        path: 'http://travmst.dev.com/home',
        title: 'MST',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: true,
        submenu: [],
      }
    ],
  },
];
