export let dummyProcessData = [
  {
    TransitionId: '1',
    FromStatus: '1007',
    FromStatusName: 'Awt Requirements',
    ToStatus: '1001',
    ToStatusName: 'Awt Ang Development',
    childs: [
      {
        TransitionId: '5',
        FromStatus: '1001',
        FromStatusName: 'Awt Ang Development',
        ToStatus: '1007',
        ToStatusName: 'Awt Requirements',
      },
      {
        TransitionId: '6',
        FromStatus: '1001',
        FromStatusName: 'Awt Ang Development',
        ToStatus: '1002',
        ToStatusName: 'Awt Java Development',
        childs: [
          {
            TransitionId: '8',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '9',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
          {
            TransitionId: '26',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1013',
            ToStatusName: 'Awt UAT Deployment',
            childs: [
              {
                TransitionId: '16',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '27',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1012',
                ToStatusName: 'Awt Testing',
                childs: [
                  {
                    TransitionId: '12',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1001',
                    ToStatusName: 'Awt Ang Development',
                  },
                  {
                    TransitionId: '13',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1002',
                    ToStatusName: 'Awt Java Development',
                  },
                  {
                    TransitionId: '14',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1007',
                    ToStatusName: 'Awt Requirements',
                  },
                  {
                    TransitionId: '15',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1013',
                    ToStatusName: 'Awt UAT Deployment',
                  },
                  {
                    TransitionId: '28',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1010',
                    ToStatusName: 'Awt PROD Deployment',
                  },
                  {
                    TransitionId: '40',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1030',
                    ToStatusName: 'Parked',
                    childs: [
                      {
                        TransitionId: '42',
                        FromStatus: '1030',
                        FromStatusName: 'Parked',
                        ToStatus: '1001',
                        ToStatusName: 'Awt Ang Development',
                      },
                      {
                        TransitionId: '43',
                        FromStatus: '1030',
                        FromStatusName: 'Parked',
                        ToStatus: '1002',
                        ToStatusName: 'Awt Java Development',
                      },
                      {
                        TransitionId: '44',
                        FromStatus: '1030',
                        FromStatusName: 'Parked',
                        ToStatus: '1007',
                        ToStatusName: 'Awt Requirements',
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '34',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1012',
            ToStatusName: 'Awt Testing',
            childs: [
              {
                TransitionId: '12',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '13',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '14',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
              {
                TransitionId: '15',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1013',
                ToStatusName: 'Awt UAT Deployment',
              },
              {
                TransitionId: '28',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '40',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1030',
                ToStatusName: 'Parked',
                childs: [
                  {
                    TransitionId: '42',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1001',
                    ToStatusName: 'Awt Ang Development',
                  },
                  {
                    TransitionId: '43',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1002',
                    ToStatusName: 'Awt Java Development',
                  },
                  {
                    TransitionId: '44',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1007',
                    ToStatusName: 'Awt Requirements',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '39',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1030',
            ToStatusName: 'Parked',
            childs: [
              {
                TransitionId: '42',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '43',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '44',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
            ],
          },
        ],
      },
      {
        TransitionId: '7',
        FromStatus: '1001',
        FromStatusName: 'Awt Ang Development',
        ToStatus: '1012',
        ToStatusName: 'Awt Testing',
        childs: [
          {
            TransitionId: '12',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '13',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '14',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
          {
            TransitionId: '15',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1013',
            ToStatusName: 'Awt UAT Deployment',
            childs: [
              {
                TransitionId: '16',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '27',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1012',
                ToStatusName: 'Awt Testing',
              },
            ],
          },
          {
            TransitionId: '28',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1010',
            ToStatusName: 'Awt PROD Deployment',
            childs: [
              {
                TransitionId: '29',
                FromStatus: '1010',
                FromStatusName: 'Awt PROD Deployment',
                ToStatus: '1011',
                ToStatusName: 'Deployed to Prod',
                childs: [
                  {
                    TransitionId: '30',
                    FromStatus: '1011',
                    FromStatusName: 'Deployed to Prod',
                    ToStatus: '1005',
                    ToStatusName: 'Closed',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '40',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1030',
            ToStatusName: 'Parked',
            childs: [
              {
                TransitionId: '42',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '43',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '44',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
            ],
          },
        ],
      },
      {
        TransitionId: '38',
        FromStatus: '1001',
        FromStatusName: 'Awt Ang Development',
        ToStatus: '1030',
        ToStatusName: 'Parked',
        childs: [
          {
            TransitionId: '42',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '43',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '44',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
        ],
      },
    ],
  },
  {
    TransitionId: '2',
    FromStatus: '1007',
    FromStatusName: 'Awt Requirements',
    ToStatus: '1006',
    ToStatusName: 'Awt UX Design',
    childs: [
      {
        TransitionId: '10',
        FromStatus: '1006',
        FromStatusName: 'Awt UX Design',
        ToStatus: '1001',
        ToStatusName: 'Awt Ang Development',
      },
      {
        TransitionId: '11',
        FromStatus: '1006',
        FromStatusName: 'Awt UX Design',
        ToStatus: '1002',
        ToStatusName: 'Awt Java Development',
        childs: [
          {
            TransitionId: '8',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '9',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
          {
            TransitionId: '26',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1013',
            ToStatusName: 'Awt UAT Deployment',
            childs: [
              {
                TransitionId: '16',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '27',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1012',
                ToStatusName: 'Awt Testing',
                childs: [
                  {
                    TransitionId: '12',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1001',
                    ToStatusName: 'Awt Ang Development',
                  },
                  {
                    TransitionId: '13',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1002',
                    ToStatusName: 'Awt Java Development',
                  },
                  {
                    TransitionId: '14',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1007',
                    ToStatusName: 'Awt Requirements',
                  },
                  {
                    TransitionId: '15',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1013',
                    ToStatusName: 'Awt UAT Deployment',
                  },
                  {
                    TransitionId: '28',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1010',
                    ToStatusName: 'Awt PROD Deployment',
                  },
                  {
                    TransitionId: '40',
                    FromStatus: '1012',
                    FromStatusName: 'Awt Testing',
                    ToStatus: '1030',
                    ToStatusName: 'Parked',
                    childs: [
                      {
                        TransitionId: '42',
                        FromStatus: '1030',
                        FromStatusName: 'Parked',
                        ToStatus: '1001',
                        ToStatusName: 'Awt Ang Development',
                      },
                      {
                        TransitionId: '43',
                        FromStatus: '1030',
                        FromStatusName: 'Parked',
                        ToStatus: '1002',
                        ToStatusName: 'Awt Java Development',
                      },
                      {
                        TransitionId: '44',
                        FromStatus: '1030',
                        FromStatusName: 'Parked',
                        ToStatus: '1007',
                        ToStatusName: 'Awt Requirements',
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '34',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1012',
            ToStatusName: 'Awt Testing',
            childs: [
              {
                TransitionId: '12',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '13',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '14',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
              {
                TransitionId: '15',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1013',
                ToStatusName: 'Awt UAT Deployment',
              },
              {
                TransitionId: '28',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '40',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1030',
                ToStatusName: 'Parked',
                childs: [
                  {
                    TransitionId: '42',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1001',
                    ToStatusName: 'Awt Ang Development',
                  },
                  {
                    TransitionId: '43',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1002',
                    ToStatusName: 'Awt Java Development',
                  },
                  {
                    TransitionId: '44',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1007',
                    ToStatusName: 'Awt Requirements',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '39',
            FromStatus: '1002',
            FromStatusName: 'Awt Java Development',
            ToStatus: '1030',
            ToStatusName: 'Parked',
            childs: [
              {
                TransitionId: '42',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '43',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '44',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
            ],
          },
        ],
      },
      {
        TransitionId: '41',
        FromStatus: '1006',
        FromStatusName: 'Awt UX Design',
        ToStatus: '1030',
        ToStatusName: 'Parked',
        childs: [
          {
            TransitionId: '42',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '43',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '44',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
        ],
      },
      {
        TransitionId: '45',
        FromStatus: '1006',
        FromStatusName: 'Awt UX Design',
        ToStatus: '1018',
        ToStatusName: 'Awt PHP Dev',
        childs: [
          {
            TransitionId: '19',
            FromStatus: '1018',
            FromStatusName: 'Awt PHP Dev',
            ToStatus: '1012',
            ToStatusName: 'Awt Testing',
            childs: [
              {
                TransitionId: '12',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '13',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '14',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
              {
                TransitionId: '15',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1013',
                ToStatusName: 'Awt UAT Deployment',
                childs: [
                  {
                    TransitionId: '16',
                    FromStatus: '1013',
                    FromStatusName: 'Awt UAT Deployment',
                    ToStatus: '1010',
                    ToStatusName: 'Awt PROD Deployment',
                    childs: [
                      {
                        TransitionId: '29',
                        FromStatus: '1010',
                        FromStatusName: 'Awt PROD Deployment',
                        ToStatus: '1011',
                        ToStatusName: 'Deployed to Prod',
                        childs: [
                          {
                            TransitionId: '30',
                            FromStatus: '1011',
                            FromStatusName: 'Deployed to Prod',
                            ToStatus: '1005',
                            ToStatusName: 'Closed',
                          },
                        ],
                      },
                    ],
                  },
                  {
                    TransitionId: '27',
                    FromStatus: '1013',
                    FromStatusName: 'Awt UAT Deployment',
                    ToStatus: '1012',
                    ToStatusName: 'Awt Testing',
                  },
                ],
              },
              {
                TransitionId: '28',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '40',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1030',
                ToStatusName: 'Parked',
              },
            ],
          },
          {
            TransitionId: '20',
            FromStatus: '1018',
            FromStatusName: 'Awt PHP Dev',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '22',
            FromStatus: '1018',
            FromStatusName: 'Awt PHP Dev',
            ToStatus: '1013',
            ToStatusName: 'Awt UAT Deployment',
            childs: [
              {
                TransitionId: '16',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '27',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1012',
                ToStatusName: 'Awt Testing',
              },
            ],
          },
          {
            TransitionId: '23',
            FromStatus: '1018',
            FromStatusName: 'Awt PHP Dev',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
        ],
      },
    ],
  },
  {
    TransitionId: '3',
    FromStatus: '1007',
    FromStatusName: 'Awt Requirements',
    ToStatus: '1002',
    ToStatusName: 'Awt Java Development',
    childs: [
      {
        TransitionId: '8',
        FromStatus: '1002',
        FromStatusName: 'Awt Java Development',
        ToStatus: '1001',
        ToStatusName: 'Awt Ang Development',
      },
      {
        TransitionId: '9',
        FromStatus: '1002',
        FromStatusName: 'Awt Java Development',
        ToStatus: '1007',
        ToStatusName: 'Awt Requirements',
      },
      {
        TransitionId: '26',
        FromStatus: '1002',
        FromStatusName: 'Awt Java Development',
        ToStatus: '1013',
        ToStatusName: 'Awt UAT Deployment',
        childs: [
          {
            TransitionId: '16',
            FromStatus: '1013',
            FromStatusName: 'Awt UAT Deployment',
            ToStatus: '1010',
            ToStatusName: 'Awt PROD Deployment',
            childs: [
              {
                TransitionId: '29',
                FromStatus: '1010',
                FromStatusName: 'Awt PROD Deployment',
                ToStatus: '1011',
                ToStatusName: 'Deployed to Prod',
                childs: [
                  {
                    TransitionId: '30',
                    FromStatus: '1011',
                    FromStatusName: 'Deployed to Prod',
                    ToStatus: '1005',
                    ToStatusName: 'Closed',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '27',
            FromStatus: '1013',
            FromStatusName: 'Awt UAT Deployment',
            ToStatus: '1012',
            ToStatusName: 'Awt Testing',
            childs: [
              {
                TransitionId: '12',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '13',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '14',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
              {
                TransitionId: '15',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1013',
                ToStatusName: 'Awt UAT Deployment',
              },
              {
                TransitionId: '28',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
              },
              {
                TransitionId: '40',
                FromStatus: '1012',
                FromStatusName: 'Awt Testing',
                ToStatus: '1030',
                ToStatusName: 'Parked',
                childs: [
                  {
                    TransitionId: '42',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1001',
                    ToStatusName: 'Awt Ang Development',
                  },
                  {
                    TransitionId: '43',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1002',
                    ToStatusName: 'Awt Java Development',
                  },
                  {
                    TransitionId: '44',
                    FromStatus: '1030',
                    FromStatusName: 'Parked',
                    ToStatus: '1007',
                    ToStatusName: 'Awt Requirements',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        TransitionId: '34',
        FromStatus: '1002',
        FromStatusName: 'Awt Java Development',
        ToStatus: '1012',
        ToStatusName: 'Awt Testing',
        childs: [
          {
            TransitionId: '12',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '13',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '14',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
          {
            TransitionId: '15',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1013',
            ToStatusName: 'Awt UAT Deployment',
          },
          {
            TransitionId: '28',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1010',
            ToStatusName: 'Awt PROD Deployment',
            childs: [
              {
                TransitionId: '29',
                FromStatus: '1010',
                FromStatusName: 'Awt PROD Deployment',
                ToStatus: '1011',
                ToStatusName: 'Deployed to Prod',
                childs: [
                  {
                    TransitionId: '30',
                    FromStatus: '1011',
                    FromStatusName: 'Deployed to Prod',
                    ToStatus: '1005',
                    ToStatusName: 'Closed',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '40',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1030',
            ToStatusName: 'Parked',
            childs: [
              {
                TransitionId: '42',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '43',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '44',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
            ],
          },
        ],
      },
      {
        TransitionId: '39',
        FromStatus: '1002',
        FromStatusName: 'Awt Java Development',
        ToStatus: '1030',
        ToStatusName: 'Parked',
        childs: [
          {
            TransitionId: '42',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '43',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '44',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
        ],
      },
    ],
  },
  {
    TransitionId: '4',
    FromStatus: '1007',
    FromStatusName: 'Awt Requirements',
    ToStatus: '1004',
    ToStatusName: 'Cancelled by User',
  },
  {
    TransitionId: '21',
    FromStatus: '1007',
    FromStatusName: 'Awt Requirements',
    ToStatus: '1018',
    ToStatusName: 'Awt PHP Dev',
    childs: [
      {
        TransitionId: '19',
        FromStatus: '1018',
        FromStatusName: 'Awt PHP Dev',
        ToStatus: '1012',
        ToStatusName: 'Awt Testing',
        childs: [
          {
            TransitionId: '12',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '13',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '14',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
          {
            TransitionId: '15',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1013',
            ToStatusName: 'Awt UAT Deployment',
            childs: [
              {
                TransitionId: '16',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1010',
                ToStatusName: 'Awt PROD Deployment',
                childs: [
                  {
                    TransitionId: '29',
                    FromStatus: '1010',
                    FromStatusName: 'Awt PROD Deployment',
                    ToStatus: '1011',
                    ToStatusName: 'Deployed to Prod',
                    childs: [
                      {
                        TransitionId: '30',
                        FromStatus: '1011',
                        FromStatusName: 'Deployed to Prod',
                        ToStatus: '1005',
                        ToStatusName: 'Closed',
                      },
                    ],
                  },
                ],
              },
              {
                TransitionId: '27',
                FromStatus: '1013',
                FromStatusName: 'Awt UAT Deployment',
                ToStatus: '1012',
                ToStatusName: 'Awt Testing',
              },
            ],
          },
          {
            TransitionId: '28',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1010',
            ToStatusName: 'Awt PROD Deployment',
            childs: [
              {
                TransitionId: '29',
                FromStatus: '1010',
                FromStatusName: 'Awt PROD Deployment',
                ToStatus: '1011',
                ToStatusName: 'Deployed to Prod',
                childs: [
                  {
                    TransitionId: '30',
                    FromStatus: '1011',
                    FromStatusName: 'Deployed to Prod',
                    ToStatus: '1005',
                    ToStatusName: 'Closed',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '40',
            FromStatus: '1012',
            FromStatusName: 'Awt Testing',
            ToStatus: '1030',
            ToStatusName: 'Parked',
            childs: [
              {
                TransitionId: '42',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1001',
                ToStatusName: 'Awt Ang Development',
              },
              {
                TransitionId: '43',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1002',
                ToStatusName: 'Awt Java Development',
              },
              {
                TransitionId: '44',
                FromStatus: '1030',
                FromStatusName: 'Parked',
                ToStatus: '1007',
                ToStatusName: 'Awt Requirements',
              },
            ],
          },
        ],
      },
      {
        TransitionId: '20',
        FromStatus: '1018',
        FromStatusName: 'Awt PHP Dev',
        ToStatus: '1002',
        ToStatusName: 'Awt Java Development',
      },
      {
        TransitionId: '22',
        FromStatus: '1018',
        FromStatusName: 'Awt PHP Dev',
        ToStatus: '1013',
        ToStatusName: 'Awt UAT Deployment',
        childs: [
          {
            TransitionId: '16',
            FromStatus: '1013',
            FromStatusName: 'Awt UAT Deployment',
            ToStatus: '1010',
            ToStatusName: 'Awt PROD Deployment',
            childs: [
              {
                TransitionId: '29',
                FromStatus: '1010',
                FromStatusName: 'Awt PROD Deployment',
                ToStatus: '1011',
                ToStatusName: 'Deployed to Prod',
                childs: [
                  {
                    TransitionId: '30',
                    FromStatus: '1011',
                    FromStatusName: 'Deployed to Prod',
                    ToStatus: '1005',
                    ToStatusName: 'Closed',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '27',
            FromStatus: '1013',
            FromStatusName: 'Awt UAT Deployment',
            ToStatus: '1012',
            ToStatusName: 'Awt Testing',
          },
        ],
      },
      {
        TransitionId: '23',
        FromStatus: '1018',
        FromStatusName: 'Awt PHP Dev',
        ToStatus: '1007',
        ToStatusName: 'Awt Requirements',
      },
    ],
  },
  {
    TransitionId: '31',
    FromStatus: '1007',
    FromStatusName: 'Awt Requirements',
    ToStatus: '1026',
    ToStatusName: 'PoH',
    childs: [
      {
        TransitionId: '32',
        FromStatus: '1026',
        FromStatusName: 'PoH',
        ToStatus: '1007',
        ToStatusName: 'Awt Requirements',
      },
      {
        TransitionId: '33',
        FromStatus: '1026',
        FromStatusName: 'PoH',
        ToStatus: '1004',
        ToStatusName: 'Cancelled by User',
      },
    ],
  },
  {
    TransitionId: '46',
    FromStatus: '1007',
    FromStatusName: 'Awt Requirements',
    ToStatus: '1012',
    ToStatusName: 'Awt Testing',
    childs: [
      {
        TransitionId: '12',
        FromStatus: '1012',
        FromStatusName: 'Awt Testing',
        ToStatus: '1001',
        ToStatusName: 'Awt Ang Development',
      },
      {
        TransitionId: '13',
        FromStatus: '1012',
        FromStatusName: 'Awt Testing',
        ToStatus: '1002',
        ToStatusName: 'Awt Java Development',
      },
      {
        TransitionId: '14',
        FromStatus: '1012',
        FromStatusName: 'Awt Testing',
        ToStatus: '1007',
        ToStatusName: 'Awt Requirements',
      },
      {
        TransitionId: '15',
        FromStatus: '1012',
        FromStatusName: 'Awt Testing',
        ToStatus: '1013',
        ToStatusName: 'Awt UAT Deployment',
        childs: [
          {
            TransitionId: '16',
            FromStatus: '1013',
            FromStatusName: 'Awt UAT Deployment',
            ToStatus: '1010',
            ToStatusName: 'Awt PROD Deployment',
            childs: [
              {
                TransitionId: '29',
                FromStatus: '1010',
                FromStatusName: 'Awt PROD Deployment',
                ToStatus: '1011',
                ToStatusName: 'Deployed to Prod',
                childs: [
                  {
                    TransitionId: '30',
                    FromStatus: '1011',
                    FromStatusName: 'Deployed to Prod',
                    ToStatus: '1005',
                    ToStatusName: 'Closed',
                  },
                ],
              },
            ],
          },
          {
            TransitionId: '27',
            FromStatus: '1013',
            FromStatusName: 'Awt UAT Deployment',
            ToStatus: '1012',
            ToStatusName: 'Awt Testing',
          },
        ],
      },
      {
        TransitionId: '28',
        FromStatus: '1012',
        FromStatusName: 'Awt Testing',
        ToStatus: '1010',
        ToStatusName: 'Awt PROD Deployment',
        childs: [
          {
            TransitionId: '29',
            FromStatus: '1010',
            FromStatusName: 'Awt PROD Deployment',
            ToStatus: '1011',
            ToStatusName: 'Deployed to Prod',
            childs: [
              {
                TransitionId: '30',
                FromStatus: '1011',
                FromStatusName: 'Deployed to Prod',
                ToStatus: '1005',
                ToStatusName: 'Closed',
              },
            ],
          },
        ],
      },
      {
        TransitionId: '40',
        FromStatus: '1012',
        FromStatusName: 'Awt Testing',
        ToStatus: '1030',
        ToStatusName: 'Parked',
        childs: [
          {
            TransitionId: '42',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1001',
            ToStatusName: 'Awt Ang Development',
          },
          {
            TransitionId: '43',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1002',
            ToStatusName: 'Awt Java Development',
          },
          {
            TransitionId: '44',
            FromStatus: '1030',
            FromStatusName: 'Parked',
            ToStatus: '1007',
            ToStatusName: 'Awt Requirements',
          },
        ],
      },
    ],
  },
];
